version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: dotnet restore
before_test:
- cmd: dotnet restore
test_script:
- cmd: dotnet test tests\CommandRouter.Tests\CommandRouter.Tests.csproj
after_test:
- cmd: dotnet pack src\CommandRouter\CommandRouter.csproj --configuration Release
- cmd: dotnet pack src\CommandRouter.Integration.AspNetCore\CommandRouter.Integration.AspNetCore.csproj --configuration Release
artifacts:
- path: src\CommandRouter\bin\Release\CommandRouter.*.nupkg
- path: src\CommandRouter.Integration.AspNetCore\bin\Release\CommandRouter.Integration.AspNetCore.*.nupkg
